# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
                ('completed', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'session',
            },
        ),
        migrations.CreateModel(
            name='SessionValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.Session')),
            ],
            options={
                'db_table': 'session_values',
            },
        ),
        migrations.CreateModel(
            name='WorkoutTypeFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('units_of_measure', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'workout_type_fields',
            },
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercises',
        ),
        migrations.AddField(
            model_name='workout',
            name='completed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exercises.WorkoutType'),
        ),
        migrations.AlterModelTable(
            name='exercise',
            table='exercise',
        ),
        migrations.AlterModelTable(
            name='workout',
            table='workout',
        ),
        migrations.AlterModelTable(
            name='workouttype',
            table='workout_type',
        ),
        migrations.DeleteModel(
            name='WorkoutExercise',
        ),
        migrations.AddField(
            model_name='workouttypefields',
            name='workout_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.WorkoutType'),
        ),
        migrations.AddField(
            model_name='sessionvalues',
            name='workout_type_fields',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.WorkoutTypeFields'),
        ),
        migrations.AddField(
            model_name='session',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.Exercise'),
        ),
        migrations.AddField(
            model_name='session',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.Workout'),
        ),
    ]
