# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'FITNESS_exercise_sessions',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('sets', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'FITNESS_session',
            },
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(related_name='workouts', through='exercises.WorkoutExercise', to='exercises.Exercise'),
        ),
        migrations.AlterModelTable(
            name='exercise',
            table='FITNESS_exercise',
        ),
        migrations.AlterModelTable(
            name='workout',
            table='FITNESS_workout',
        ),
        migrations.AlterModelTable(
            name='workoutexercise',
            table='FITNESS_workouts_exercises',
        ),
        migrations.AlterModelTable(
            name='workouttype',
            table='FITNESS_workout_type',
        ),
        migrations.AddField(
            model_name='exercisesession',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.Exercise'),
        ),
        migrations.AddField(
            model_name='exercisesession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.Session'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercises',
            field=models.ManyToManyField(related_name='exercises', through='exercises.ExerciseSession', to='exercises.Session'),
        ),
    ]
