# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20170512_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='exercises.Exercise'),
        ),
        migrations.AlterField(
            model_name='session',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='exercises.Workout'),
        ),
        migrations.AlterField(
            model_name='sessionvalues',
            name='workout_type_fields',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_values', to='exercises.WorkoutTypeFields'),
        ),
        migrations.AlterField(
            model_name='workouttypefields',
            name='workout_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_type_fields', to='exercises.WorkoutType'),
        ),
    ]
