# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20170508_0926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='exercises',
            new_name='sessions',
        ),
    ]
