# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_auto_20170512_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='exercises.Exercise'),
        ),
        migrations.AlterField(
            model_name='sessionvalues',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_values', to='exercises.Session'),
        ),
    ]
