# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_auto_20170508_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.CharField(default='workout 8-5-2017-22h0001-01-01 00:00:00m36s', max_length=255),
        ),
    ]
