# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_auto_20170512_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('units_of_measure', models.CharField(max_length=255, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_fields', to='exercises.Exercise')),
            ],
            options={
                'db_table': 'exercise_fields',
            },
        ),
        migrations.RemoveField(
            model_name='workouttypefields',
            name='workout_type',
        ),
        migrations.RemoveField(
            model_name='sessionvalues',
            name='workout_type_fields',
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.WorkoutType'),
        ),
        migrations.DeleteModel(
            name='WorkoutTypeFields',
        ),
        migrations.AddField(
            model_name='sessionvalues',
            name='exercise_fields',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='session_values', to='exercises.ExerciseFields'),
        ),
    ]
