# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_auto_20170513_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout', to='exercises.WorkoutType'),
        ),
    ]
