# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_workout_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(default='workout 9-5-2017-11h0001-01-01 00:00:00m4s', max_length=255),
        ),
    ]
