# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_auto_20170514_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisefields',
            name='exercise',
        ),
        migrations.AddField(
            model_name='exercisefields',
            name='exercise',
            field=models.ManyToManyField(related_name='exercise_fields', to='exercises.Exercise'),
        ),
    ]
