# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_remove_workout_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='completed',
            field=models.DateTimeField(null=True),
        ),
    ]
